spring:
  application:
    name: ZeriExLanguage

  datasource:
    # 💡 連結到你剛才 Docker 跑起來的資料庫
    url: jdbc:postgresql://localhost:5432/zeri_lang_db
    username: zeri
    password: yes54425
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always # 💡 強制每次啟動都檢查並執行 SQL 腳本

  jpa:
    defer-datasource-initialization: true # 💡 確保 Table 建好後才跑 SQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# 保持 server 設定不變
server:
  port: 8080